import{getClient,session,friendlyError}from'./supabase.js';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
export function toast(text){const n=document.createElement('div');n.className='toast';n.setAttribute('role','status');n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),3500)}
function header(){const h=$('[data-header]');if(!h)return;h.innerHTML=`<a class="skip" href="#main">მთავარ შინაარსზე გადასვლა</a><header class="site-header"><nav class="container nav" aria-label="მთავარი"><a class="brand" href="index.html"><img src="assets/favicon.svg" alt=""><span>იურისტი</span></a><button class="btn secondary menu-btn" aria-label="მენიუს გახსნა">☰</button><div class="nav-links"><a href="tests.html">ტესტები</a><a href="quick-test.html">სწრაფი ტესტი</a><a href="laws.html">კანონები</a><a href="leaderboard.html">რეიტინგი</a><a href="about.html">ჩვენს შესახებ</a></div><div class="nav-actions"><a class="btn secondary" href="auth.html">შესვლა</a><a class="btn" href="quick-test.html">სწრაფი ტესტი</a></div></nav></header>`;$('.menu-btn').onclick=()=>$('.nav-links').classList.toggle('open')}
function footer(){const f=$('[data-footer]');if(f)f.innerHTML=`<footer class="footer"><div class="container footer-grid"><div><b>იურისტი</b><p>ისწავლე სამართალი პრაქტიკული ტესტებით.</p></div><div><a href="certificate.html">სერტიფიკატის შემოწმება</a><p>© 2026 ყველა უფლება დაცულია</p></div></div></footer>`}
async function signOut(){const c=await getClient();if(c)await c.auth.signOut();location.href='index.html'}
async function authState(){const s=await session();if(!s)return;$$('.nav-actions').forEach(n=>{n.replaceChildren();const wrap=document.createElement('div');wrap.className='profile-menu';const a=document.createElement('a');a.className='btn';a.href='profile.html';a.textContent='ჩემი პროფილი';const out=document.createElement('button');out.type='button';out.className='profile-menu-signout';out.textContent='გამოსვლა';out.onclick=signOut;wrap.append(a,out);n.append(wrap)})}
export async function rpc(name,args={}){const c=await getClient();if(!c)throw new Error('დემო რეჟიმი');try{const{data,error}=await c.rpc(name,args);if(error)throw error;return data}catch(e){throw new Error(friendlyError(e))}}
header();footer();authState();window.addEventListener('offline',()=>toast('ინტერნეტთან კავშირი გაწყდა. მონაცემები დროებით შეინახება.'));window.App={toast,rpc,getClient,friendlyError};
